# Replication code to geolocate IP addresses

First, you need a code to get from the internet the coordinates from inputted IP addresses. We will use `ipgeolocation.io`.

The function `freegeoip()` takes an IP address as the input and will return a list of  
```{r}
require(rjson)
## Function for fetching and converting IP address geo-coordinates

freegeoip <- function(ip, format = ifelse(length(ip)==1,'dataframe','dataframe'))
{
    if (1 == length(ip))
    {
        # a single IP address
        require(rjson)
        url <- paste(c("https://api.ipgeolocation.io/ipgeo?apiKey=d46e7c1556fb42e3806ad46491fade5d&ip=", ip), collapse='')
        ret <- fromJSON(readLines(url, warn=FALSE))
        if (format == 'dataframe')
            ret <- data.frame(t(unlist(ret)))
        return(ret)
    } else {
        ret <- data.frame()
        for (i in 1:length(ip))
        {
            r <- freegeoip(ip[i], format="dataframe")
            ret <- rbind(ret, r)
        }
        return(ret)
    }
}   
```


```{r}
## Read in IP addresses
ip <- read.csv("https://raw.githubusercontent.com/jcervas/R-Functions/main/ignacio/data/ip.csv")

## Loop through each IP address and return geo-coordinates. If there is an error, move to next.
for (i in 1:nrow(ip)) {
       skip_to_next <- FALSE

  tryCatch(geo[i,] <- freegeoip(ip[i,]), error = function(e) {skip_to_next <<- TRUE})

  if(skip_to_next) { next } 
     
}
```

```{r}
head(geo)
write.csv(geo, "/Users/cervas/My Drive/GitHub/R-Functions/ignacio/data/geocode-ip.cvs", row.names=F)
```

